x-kafka-defaults: &kafka-defaults
  image: strimzi/example-kafka
  env_file:
    - variables.env
  cap_add:
    - NET_ADMIN
  deploy:
    resources:
      limits:
        cpus: '2'

services:

  #################################### KAFKA BROKER ####################################
  kafka-1:
    <<: *kafka-defaults  
    build: kafka
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - 40001:9092

      # javaagent debug port
      #- 5005:5005

    environment:

      # Java Debug
      #KAFKA_DEBUG: y
      #DEBUG_SUSPEND_FLAG: y
      #JAVA_DEBUG_PORT: 5005

      #
      # KAFKA Configuration
      #
      KAFKA_NODE_ID: "1"

  kafka-2:
    <<: *kafka-defaults  
    build: kafka
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - 40002:9092
    environment:
      KAFKA_NODE_ID: "2"

  kafka-3:
    <<: *kafka-defaults  
    build: kafka
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - 40003:9092
    environment:
      KAFKA_NODE_ID: "3"

  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka-1:9093
      SERVER_SERVLET_CONTEXTPATH: "/"
    deploy:
      resources:
        limits:
          cpus: '1'

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.5
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
      - ./keycloak/certificates/keycloak.server.keystore.p12:/opt/keycloak/data/certs/keycloak.server.keystore.p12

    command: "-v start --import-realm --features=token-exchange,authorization,scripts --https-key-store-file=/opt/keycloak/data/certs/keycloak.server.keystore.p12 --https-key-store-password=changeit"

    environment:      
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_ADMIN_URL=http://localhost:8080/
      - KC_HTTP_ENABLED=true
      # - KC_HOSTNAME_STRICT=false
      # - KC_HOSTNAME_STRICT_HTTPS=false
      # - KC_HOSTNAME_PORT=8080
      # - KC_HOSTNAME=localhost
      
networks:
  default:
    name: kafka