---
version: '2'

x-kafka-defaults: &kafka-defaults
  image: apache/kafka
  env_file:
    - variables.env
  #volumes:
    # - ./log4j-debug.properties:/mnt/shared/config/log4j.properties
  deploy:
    resources:
      limits:
        cpus: '2'

services:
  kafka-1: &kafka-base
    <<: *kafka-defaults
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - 40001:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,PLAINTEXT_HOST://localhost:40001

  kafka-2:
    <<: *kafka-defaults
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - 40002:9092
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:19092,PLAINTEXT_HOST://localhost:40002

  kafka-3:
    <<: *kafka-defaults
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - 40003:9092
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:19092,PLAINTEXT_HOST://localhost:40003

  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka-1:19092
      SERVER_SERVLET_CONTEXTPATH: "/"
    deploy:
      resources:
        limits:
          cpus: '1'

networks:
  default:
    name: kafka