---
version: '2'

x-kafka-defaults: &kafka-defaults
  image: apache/kafka
# image: mykafka
  env_file:
    - variables.env
  cap_add:
    - NET_ADMIN
  #volumes:
    # - ./log4j-debug.properties:/mnt/shared/config/log4j.properties
  deploy:
    resources:
      limits:
        cpus: '2'
        
  # tc qdisc add dev eth0 root netem loss 20%
  # tc qdisc add dev eth0 root netem delay 400ms && \
  #command: >
  #    bash -c "
  #    /etc/kafka/docker/run
  #    "
services:
  kafka-1: &kafka-base
    <<: *kafka-defaults
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - 40001:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,PLAINTEXT_HOST://localhost:40001

  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka-1:19092
      SERVER_SERVLET_CONTEXTPATH: "/"
    deploy:
      resources:
        limits:
          cpus: '1'

networks:
  default:
    name: kafka